services:
  - type: web
    name: blockbusted
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    preDeployCommand: |
      python manage.py migrate
    startCommand: |
      gunicorn blockbusted.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: DATABASE_URL
        fromDatabase:
          name: blockbusted-db
          property: connectionString

databases:
  - name: blockbusted-db
    plan: free
